import { AnimateBorder, AnimateThreeDotCard, MotionOnscreen, SubTitle } from 'components';
import { FC, ReactElement } from 'react';

import styles from './index.module.scss';

const TradingRules: FC = (): ReactElement => {
  return (
    <section className={styles.container}>
      <SubTitle>WKT Trading Rules</SubTitle>

      <div className={styles.timeMapBg}>
        <div className={styles.timeMap}>
          <MotionOnscreen postition='scale'>
            <h1>Time Map</h1>
          </MotionOnscreen>
          <MotionOnscreen postition='scale'>
            <div className={styles.text}>Cost of Getting 1 WKT</div>
          </MotionOnscreen>
          <div className={styles.roundBack}>
            <div className={styles.leftBlcok}>
              <span>Pre-digging in Class</span>
            </div>
            <div className={styles.rightBlock}>
              <span>Free Trade</span>
            </div>
            <div className={styles.priceLine}>
              <div className={styles.item}>$0.1</div>
              <div className={styles.item}>$1</div>
              <div className={styles.item}>$10</div>
              <div className={styles.item}>$100</div>
              <div className={styles.item}>$10000</div>
            </div>
            <div className={styles.appLaunched}>APP Launched</div>
            <div className={styles.initialTrade}>
              01-03-2023
              <br />
              WKT Opening Price
            </div>
          </div>
        </div>
      </div>

      <AnimateThreeDotCard className={styles.card}>
        <MotionOnscreen postition='scale'>
          <AnimateBorder animateCount={2} className={styles.title}>
            <div className={styles.titleContent}>Trade Opening Hours</div>
          </AnimateBorder>
        </MotionOnscreen>
        <MotionOnscreen postition='scale'>
          <div>
            WKT will officially open for trading at 00:00 UTC 1st March 2023. Before the official
            opening of trading, users can obtain WKT by having classes in Metaclassn
          </div>
        </MotionOnscreen>
      </AnimateThreeDotCard>

      <AnimateThreeDotCard className={styles.card}>
        <MotionOnscreen postition='scale'>
          <AnimateBorder animateCount={2} className={styles.title}>
            <div className={styles.titleContent}>WKT Opening Price</div>
          </AnimateBorder>
        </MotionOnscreen>
        <MotionOnscreen postition='scale'>
          <div>
            The WKT recommended opening price is $10 each. Users can freely trade WKT around the
            world after WKT opens for trading
          </div>
        </MotionOnscreen>
      </AnimateThreeDotCard>

      <AnimateThreeDotCard className={styles.card}>
        <MotionOnscreen postition='scale'>
          <AnimateBorder animateCount={2} className={styles.title}>
            <div className={styles.titleContent}>Pricing Mechanism</div>
          </AnimateBorder>
        </MotionOnscreen>
        <MotionOnscreen postition='scale'>
          <div>
            Having classes on Metaclassn is the only way to generate WKT. Over time, the cost of
            each WKT generated by the platform will become higher and higher, eventually exceeding
            $100,000, so WKT will become more and more expensive; still, the actual price is up to
            the market and users to decide
          </div>
        </MotionOnscreen>
      </AnimateThreeDotCard>
    </section>
  );
};

export default TradingRules;
